### ISSUE TITLE
Support for CustomFeeds in libreddit

### ISSUE THREAD

**Issue by TrueMysterious** [libreddit/libreddit#340] opened 2021-11-24 16:29 UTC
## How does this feature work on Reddit?
Custom Feeds allow you to view a list of subreddit as a single subreddit.
[For example](https://www.reddit.com/user/Lapper/m/depthhub)
Currently [libreddit](https://libredd.it/user/Lapper/m/depthhub) will return not found page.
## Describe the implementation into Libreddit
Basic method will be to get the names of subreddit from "Communities in this custom feed" card and then redirect them to new link such as [this](https://libredd.it/r/cogsci+AskAnthropology+AskSocialScience+musictheory+Foodforthought+LetsTalkMusic+PoliticalDiscussion+neutralnews+TrueReddit+Scholar+PhilosophyofScience+TheoryOfReddit+TrueFilm+badhistory+Anthropology+AcademicBiblical+NeutralPolitics+AskBibleScholars+linguistics+AskHistorians+DepthHub+CredibleDefense+Ask_Politics+MensLib+AcademicPhilosophy+DaystromInstitute+philosophy+WarCollege+TrueAskReddit+askscience+geopolitics+askphilosophy+truegaming) .

**Comment by TheCultLeader666** [comment] 2021-11-24 17:19
Why not just use multireddits?

**Comment by TrueMysterious** [comment] 2021-11-25 05:10
currently to access something like https://www.reddit.com/user/samuraisam/m/programming/top/?t=all i will need to convert it into multreddit by writing as all subreddit to  url either manual or make a userscript to convert it for me.Even if i write a userscript to do so, It will only work on pcs not on mobile browsers.

**Comment by danjonesdev** [comment] 2021-12-09 18:39
+1, Came here to request this feature.

**Comment by spikecodes** [comment] 2022-11-03 04:02
Duplicate of #569

**Closed by spikecodes** 2022-11-03 04:02 UTC
Labels: feature parity
